language: cpp

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
    - QT_BASE=59
  - os: osx
    compiler: clang
    env:
    - QT_BASE=59

cache: packages

before_install:
- if [[ "$QT_BASE" = "59" && "$TRAVIS_OS_NAME" = "linux" ]]; then 
    sudo add-apt-repository ppa:beineri/opt-qt592-trusty -y; 
  fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; 
    sudo apt-get update -qq; 
  else 
    brew update;
  fi
- COMMIT_TIMESTAMP=`date +%Y-%m-%d`
- echo $COMMIT_TIMESTAMP

before_deploy:
  # Set up git user name and tag for this commit
  - git config --local user.name "praaline"
  - git config --local user.email "info@praaline.org"
  - git tag -f "$(date +'%Y-%m-%d')"
  
install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    sudo apt-get install -qq g++-5;
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90;
  fi
- if [ "$QT_BASE" = "59" ]; then
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get install -qq qt59base;
      source /opt/qt59/bin/qt59-env.sh;
    else
      brew install qt5;
      brew link --force qt5;
      export HOMEBREW_QT5_VERSION=$(brew list --versions qt5 | rev | cut -d' ' -f1 | rev);
      ln -s /usr/local/Cellar/qt5/$HOMEBREW_QT5_VERSION/mkspecs /usr/local/mkspecs;
    fi
  fi

script:
- g++ -v;
- qmake -v;
- qmake ./pncore.pro CONFIG+=release && make
- ls -R
- tar -czv --exclude='.*' -f pncore_${TRAVIS_OS_NAME}.tar.gz build/release

deploy:
  provider: releases
  api-key:
    secure: Q12crABoL7Oy5y9E/dC5rpE/hXCeBDnvsZkv2i9PnMxysc+qhtLfUpTehj6qheG+vSiv0y1SCylP8QyW+tkmojs7Ox94GX9vzfa0uAwJGrMb34PTzDhnVrEQla25Eq52WSbhq1sQ48kCbYuvniIziazayt72+euAooU1kGV+teeiOsRbVuNWqQbp/SpHq2R1dpWPnWQbxowy3xDWIIe7khBLWH+cOR5HBBDnz+JIGILiOid/lSY/LXwFRb8zYTmUJ65u1GoJLL//bkWWteduOwVYJCa2OOC6lOVntxrQiA3zfNVlQZinFU26uaKdBPUp3Tt3nrw2oEq40EhBq5LiIFlC68ZqsyhrG6KMslf4a6z4cqOmZ0WZfjIneegyKEtsN+//ByMFHw3VfVQjejK2Ro/mgkb+IlUd5w4jgGeHaFbYv0h1vgg4tubJGtrBDDzrAGOtcx0op18bqFZPqG/MiPFES/Hz/5n2t41Q13V5o4XcjzI4V6w5J+7pt4ahePbzNKJiluj+BJ0P7xgYsETStj+IYIXZvZ9XgF2zxtto7syt/X2c0ZNhsRZI2rn5kl18BhFpYIUK3xJGlxXLuwXZrJFOphdMUICAGEDlp4NPZlnsiylYs5hwUWYxKvCBXlEs3EUKWdp9lg5Ufn64QuVGVZ3MqZUr8cy0/LVi0BZRvoE=
  name: $(date +'%Y-%m-%d')
  file: pncore_${TRAVIS_OS_NAME}.tar.gz
  skip_cleanup: true
  on:
    repo: praaline/praaline-core
    all_branches: true

notifications:
  email: false

