version: '{build}'

init:
- git config --global core.autocrlf input

environment:
  matrix:
  - arch: x64
    QT5: C:\Qt\5.13\mingw73_64
    MINGW: C:\Qt\Tools\mingw730_64

matrix:
  fast_finish: true

before_build:
- set PATH=%MINGW%\bin;%QT5%\bin;%PATH%
- echo %PATH%
- ps: $env:COMMIT_TIMESTAMP = $(Get-Date -format yyyy-MM-dd)

build_script:
# Build Praaline Core Library
- qmake -v
- qmake .\praaline-core.pro CONFIG+=release && mingw32-make
- copy build\release\praaline-core.dll .\praaline-core.dll
- dir /s

artifacts:
- path: praaline-core.dll

deploy:
  - provider: GitHub
    release: $(COMMIT_TIMESTAMP)
    auth_token: 
      secure: QP8Fu6Yw87cA6bQ0G7hf/MPFzYw0+/wwnLKnMahrETh7gPXh5Ad/2gOIEfvGrfpn
    artifact: praaline-core.dll
    force_update: true
    on: 
      branch: master

test: off  # to avoid discovering tests
