version: '{build}'

init:
- git config --global core.autocrlf input

environment:
  matrix:
  - arch: x86
    QT5: C:\Qt\5.9.2\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
pncore.dll
matrix:
  fast_finish: true

before_build:
- set PATH=%MINGW%\bin;%QT5%\bin;%PATH%

build_script:
# Build Praaline Core Library
- qmake -v
- qmake .\pncore.pro CONFIG+=release && mingw32-make
- copy build\release\pncore.dll .\pncore.dll
- dir /s

artifacts:
- path: pncore.dll

deploy:
  - provider: GitHub
    release: $(COMMIT_TIMESTAMP)
    auth_token: 
      secure: QP8Fu6Yw87cA6bQ0G7hf/MPFzYw0+/wwnLKnMahrETh7gPXh5Ad/2gOIEfvGrfpn
    artifact: pncore.dll
    force_update: true
    on: 
      branch: master

test: off  # to avoid discovering tests
